//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Akademisyenler
    {
        public int Akademisyen_Id { get; set; }
        public string AkademisyenAd { get; set; }
        public string AkademisyenSoyad { get; set; }
        public string AkademisyenKullanıcı { get; set; }
        public string AkademisyenŞifre { get; set; }
        public Nullable<int> Bölüm_Id { get; set; }
    
        public virtual Bölümler Bölümler { get; set; }
    }
}
