//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProjesi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbOTOMASYONEntities : DbContext
    {
        public DbOTOMASYONEntities()
            : base("name=DbOTOMASYONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Akademisyenler> Akademisyenler { get; set; }
        public virtual DbSet<Bölümler> Bölümler { get; set; }
        public virtual DbSet<Öğrenciler> Öğrenciler { get; set; }
        public virtual DbSet<Projeler> Projeler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
