//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProjesi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    public partial class Öğrenciler
    {
        public int Ogrenci_Id { get; set; }
        [Required(ErrorMessage = "Adınızı Giriniz !!!")]
        public string OgrenciAd { get; set; }
        [Required(ErrorMessage = "Soyadınızı Giriniz!!!")]
        public string OgrenciSoyad { get; set; }
        [Required(ErrorMessage = "Kullanıcı Adınızı Giriniz !!!")]
        [MaxLength(9, ErrorMessage = "Kullanıcı Adı En Fazla 9 Karakterden Oluşmalıdır..")]
        [MinLength(9, ErrorMessage = "Kullanıcı Adı En Az 9 Karakterden Oluşmalıdır..")]
        public string KullanıcıAd { get; set; }
        [Required(ErrorMessage = "Şifrenizi Giriniz !!!")]
        [MaxLength(15, ErrorMessage = "Şifreniz En Fazla 15 Karakterden Oluşmalıdır..")]
        [MinLength(6, ErrorMessage = "Şifreniz  En Az 6 Karakterden Oluşmalıdır..")]
        public string Şifre { get; set; }

        public Nullable<int> Bölüm_Id { get; set; }
        public Nullable<int> Proje_Id { get; set; }
   
        public virtual Bölümler Bölümler { get; set; }
        public virtual Projeler Projeler { get; set; }
    }

}
